In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import datetime
from datetime import timedelta
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
data = pd.read_csv("/content/drive/MyDrive/superstore_sales.csv")

In [3]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
data.shape

(9800, 18)

In [5]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [7]:
data["Order Date"] = pd.to_datetime(data["Order Date"])

In [8]:
data["Ship Date"] = pd.to_datetime(data["Ship Date"])

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(13)
memory usage: 1.3+ MB

In [10]:
data[["Order ID",
      "Ship Mode",
      "Customer ID",
      "Segment",
      "Country",
      "City",
      "State",
      "Region",
      "Sub-Category",
      "Product Name"
      ]]

,Order ID,Ship Mode,Customer ID,Segment,Country,City,State,Region,Sub-Category,Product Name
0,CA-2017-152156,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,South,Bookcases,Bush Somerset Collection Bookcase
1,CA-2017-152156,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,South,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,..."
2,CA-2017-138688,Second Class,DV-13045,Corporate,United States,Los Angeles,California,West,Labels,Self-Adhesive Address Labels for Typewriters b...
3,US-2016-108966,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,South,Tables,Bretford CR4500 Series Slim Rectangular Table
4,US-2016-108966,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,South,Storage,Eldon Fold 'N Roll Cart System
...,...,...,...,...,...,...,...,...,...,...
9795,CA-2017-125920,Standard Class,SH-19975,Corporate,United States,Chicago,Illinois,Central,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St..."
9796,CA-2016-128608,Standard Class,CS-12490,Corporate,United States,Toledo,Ohio,East,Art,"BIC Brite Liner Highlighters, Chisel Tip"
9797,CA-2016-128608,Standard Class,CS-12490,Corporate,United States,Toledo,Ohio,East,Phones,GE 30524EE4
9798,CA-2016-128608,Standard Class,CS-12490,Corporate,United States,Toledo,Ohio,East,Phones,Anker 24W Portable Micro USB Car Charger
9799,CA-2016-128608,Standard Class,CS-12490,Corporate,United States,Toledo,Ohio,East,Accessories,SanDisk Cruzer 4 GB USB Flash Drive

In [11]:
col_list = ["Order ID",
      "Ship Mode",
      "Customer ID",
      "Segment",
      "Country",
      "City",
      "State",
      "Region",
      "Sub-Category",
      "Product Name"
      ]

In [12]:
data[col_list].describe()

,Order ID,Ship Mode,Customer ID,Segment,Country,City,State,Region,Sub-Category,Product Name
count,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800
unique,4922,4,793,3,1,529,49,4,17,1849
top,CA-2018-100111,Standard Class,WB-21850,Consumer,United States,New York City,California,West,Binders,Staple envelope
freq,14,5859,35,5101,9800,891,1946,3140,1492,47

In [13]:
data[["Order Date","Ship Date"]].describe()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  """Entry point for launching an IPython kernel.

                 Order Date            Ship Date
count                  9800                 9800
unique                 1230                 1326
top     2017-05-09 00:00:00  2018-09-26 00:00:00
freq                     38                   34
first   2015-01-02 00:00:00  2015-01-04 00:00:00
last    2018-12-30 00:00:00  2019-05-01 00:00:00

In [14]:
data["Ship Mode"].value_counts()

Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: Ship Mode, dtype: int64

In [15]:
col_list = ["Ship Mode","Segment","City","State","Region","Category","Sub-Category"]

In [16]:
for sütun in col_list:
  print(" ")
  print(sütun)
  print(data[sütun].value_counts())

Ship Mode
Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: Ship Mode, dtype: int64

Segment
Consumer       5101
Corporate      2953
Home Office    1746
Name: Segment, dtype: int64

City
New York City    891
Los Angeles      728
Philadelphia     532
San Francisco    500
Seattle          426
                ...
San Mateo          1
Cheyenne           1
Conway             1
Melbourne          1
Springdale         1
Name: City, Length: 529, dtype: int64

State
California              1946
New York                1097
Texas                    973
Pennsylvania             582
Washington               504
Illinois                 483
Ohio                     454
Florida                  373
Michigan                 253
North Carolina           247
Virginia                 224
Arizona                  223
Tennessee                183
Colorado                 179
Georgia                  177
Kentucky                 137
Indiana                  135
Massachusetts            135
Oregon                   122
New Jersey               122
Maryland                 105
Wisconsin                105
Delaware                  93
Minnesota                 89
Connecticut               82
Missouri                  66
Oklahoma                  66
Alabama                   61
Arkansas                  60
Rhode Island              55
Mississippi               53
Utah                      53
South Carolina            42
Louisiana                 41
Nevada                    39
Nebraska                  38
New Mexico                37
New Hampshire             27
Iowa                      26
Kansas                    24
Idaho                     21
Montana                   15
South Dakota              12
Vermont                   11
District of Columbia      10
Maine                      8
North Dakota               7
West Virginia              4
Wyoming                    1
Name: State, dtype: int64

Region
West       3140
East       2785
Central    2277
South      1598
Name: Region, dtype: int64

Category
Office Supplies    5909
Furniture          2078
Technology         1813
Name: Category, dtype: int64

Sub-Category
Binders        1492
Paper          1338
Furnishings     931
Phones          876
Storage         832
Art             785
Accessories     756
Chairs          607
Appliances      459
Labels          357
Tables          314
Envelopes       248
Bookcases       226
Fasteners       214
Supplies        184
Machines        115
Copiers          66
Name: Sub-Category, dtype: int64

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   datetime64[ns]
 3   Ship Date      9800 non-null   datetime64[ns]
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(13)
memory usage: 1.3+ MB

In [18]:
data["Ship Date"] - data["Order Date"]

0        92 days
1        92 days
2      -173 days
3       -23 days
4       -23 days
          ...
9795      7 days
9796   -319 days
9797   -319 days
9798   -319 days
9799   -319 days
Length: 9800, dtype: timedelta64[ns]

In [19]:
data["shipping_timeframe"] = data["Ship Date"] - data["Order Date"]

In [20]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92 days
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92 days
2,3,CA-2017-138688,2017-12-06,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,-173 days
3,4,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,-23 days
4,5,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,-23 days

In [21]:
data[["shipping_timeframe", "_"]] = data["shipping_timeframe"].astype("str").str.split(expand=True)

In [22]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days
2,3,CA-2017-138688,2017-12-06,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,-173,days
3,4,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,-23,days
4,5,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,-23,days

In [23]:
data["shipping_timeframe"] = data.shipping_timeframe.astype(int)

In [24]:
data.dtypes

Row ID                         int64
Order ID                      object
Order Date            datetime64[ns]
Ship Date             datetime64[ns]
Ship Mode                     object
Customer ID                   object
Customer Name                 object
Segment                       object
Country                       object
City                          object
State                         object
Postal Code                  float64
Region                        object
Product ID                    object
Category                      object
Sub-Category                  object
Product Name                  object
Sales                        float64
shipping_timeframe             int64
_                             object
dtype: object

In [25]:
data[data.shipping_timeframe < 0]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_
2,3,CA-2017-138688,2017-12-06,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,-173,days
3,4,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,-23,days
4,5,US-2016-108966,2016-11-10,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,-23,days
5,6,CA-2015-115812,2015-09-06,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,-84,days
6,7,CA-2015-115812,2015-09-06,2015-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,-84,days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9790,9791,CA-2018-144491,2018-03-27,2018-01-04,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-CH-10001714,Furniture,Chairs,"Global Leather & Oak Executive Chair, Burgundy",211.2460,-82,days
9796,9797,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680,-319,days
9797,9798,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880,-319,days
9798,9799,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760,-319,days
9799,9800,CA-2016-128608,2016-12-01,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840,-319,days

In [26]:
data_buyuk = data[data.shipping_timeframe>=0]

In [27]:
data_buyuk

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,92,days
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,92,days
12,13,CA-2018-114412,2018-04-15,2018-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,North Carolina,28027.0,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,5,days
13,14,CA-2017-161389,2017-05-12,2017-10-12,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,Washington,98103.0,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.976,153,days
14,15,US-2016-118983,2016-11-22,2016-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,4,days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9791,9792,CA-2015-127166,2015-05-21,2015-05-23,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,OFF-EN-10003134,Office Supplies,Envelopes,Staple envelope,56.064,2,days
9792,9793,CA-2015-127166,2015-05-21,2015-05-23,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,FUR-CH-10003396,Furniture,Chairs,Global Deluxe Steno Chair,107.772,2,days
9793,9794,CA-2015-127166,2015-05-21,2015-05-23,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,OFF-PA-10001560,Office Supplies,Paper,"Adams Telephone Message Books, 5 1/4” x 11”",4.832,2,days
9794,9795,CA-2015-127166,2015-05-21,2015-05-23,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,OFF-BI-10000977,Office Supplies,Binders,Ibico Plastic Spiral Binding Combs,18.240,2,days
9795,9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798,7,days

In [28]:
data["Ship Mode"].value_counts()

Standard Class    5859
Second Class      1902
First Class       1501
Same Day           538
Name: Ship Mode, dtype: int64

In [29]:
data_buyuk.groupby('Ship Mode').agg({'shipping_timeframe':'median'})

                shipping_timeframe
Ship Mode
First Class                    3.0
Same Day                       0.0
Second Class                   4.0
Standard Class                 6.0

In [30]:
data_buyuk.groupby('Ship Mode').agg({'shipping_timeframe':'mean'}).reset_index()

        Ship Mode  shipping_timeframe
0     First Class           26.311756
1        Same Day            0.891791
2    Second Class           36.224796
3  Standard Class           52.805130

In [31]:
data['Ship Date'] = np.where( 
    (data.shipping_timeframe <0) & (data['Ship Mode'] == 'First Class'),
                             data['Order Date'] + timedelta(days=3), 
                             data['Ship Date']
                             )

In [32]:
data['Ship Date'] = np.where( 
    (data.shipping_timeframe <0) & (data['Ship Mode'] == 'Same Day'),
                             data['Order Date'], 
                             data['Ship Date']
                             )

In [33]:
data['Ship Date'] = np.where( 
    (data.shipping_timeframe <0) & (data['Ship Mode'] == 'Second Class'),
                             data['Order Date']+ timedelta(days=4), 
                             data['Ship Date']
                             )

In [34]:
data['Ship Date'] = np.where( 
    (data.shipping_timeframe <0) & (data['Ship Mode'] == 'Standard Class'),
                             data['Order Date']+ timedelta(days=6), 
                             data['Ship Date']
                             )

In [35]:
ship_mode_dict = {'First Class':3,
                  'Same Day':0,
                  'Second Class':4,
                  'Standard Class':6}

In [36]:
ship_mode_dict.items()

dict_items([('First Class', 3), ('Same Day', 0), ('Second Class', 4), ('Standard Class', 6)])

In [37]:
for key,value in ship_mode_dict.items():
  data['Ship Date'] = np.where( 
    (data.shipping_timeframe <0) & (data['Ship Mode'] == key),
                             data['Order Date'] + timedelta(days=value), 
                             data['Ship Date']
                             )

In [38]:
data['shipping_timeframe'] = data['Ship Date'] - data['Order Date']

In [39]:
data[['shipping_timeframe', '_']] = data['shipping_timeframe'].astype('str').str.split(expand=True)

In [40]:
data['shipping_timeframe'] = data.shipping_timeframe.astype(int)

In [41]:
data[data.shipping_timeframe<0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, shipping_timeframe, _]
Index: []

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              9800 non-null   int64
 1   Order ID            9800 non-null   object
 2   Order Date          9800 non-null   datetime64[ns]
 3   Ship Date           9800 non-null   datetime64[ns]
 4   Ship Mode           9800 non-null   object
 5   Customer ID         9800 non-null   object
 6   Customer Name       9800 non-null   object
 7   Segment             9800 non-null   object
 8   Country             9800 non-null   object
 9   City                9800 non-null   object
 10  State               9800 non-null   object
 11  Postal Code         9789 non-null   float64
 12  Region              9800 non-null   object
 13  Product ID          9800 non-null   object
 14  Category            9800 non-null   object
 15  Sub-Category        9800 non-null   object
 16  Product Name        9800 non-null   object
 17  Sales               9800 non-null   float64
 18  shipping_timeframe  9800 non-null   int64
 19  _                   9800 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(14)
memory usage: 1.5+ MB

In [43]:
data[['City', 'State']][data['Postal Code'].isnull()].value_counts()

City        State
Burlington  Vermont    11
dtype: int64

In [44]:
data.dtypes

Row ID                         int64
Order ID                      object
Order Date            datetime64[ns]
Ship Date             datetime64[ns]
Ship Mode                     object
Customer ID                   object
Customer Name                 object
Segment                       object
Country                       object
City                          object
State                         object
Postal Code                  float64
Region                        object
Product ID                    object
Category                      object
Sub-Category                  object
Product Name                  object
Sales                        float64
shipping_timeframe             int64
_                             object
dtype: object

In [45]:
data['Postal Code'] = data['Postal Code'].fillna('05402')

In [46]:
data['Postal Code'] = data['Postal Code'].astype(float)

In [47]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days

In [48]:
# daily sales

In [49]:
data_daily_sales = data.groupby('Order Date').agg({"Sales":'sum'}).reset_index()

In [50]:
data_daily_sales

     Order Date      Sales
0    2015-01-02   468.9000
1    2015-01-03  2203.1510
2    2015-01-04   119.8880
3    2015-01-06  5188.5200
4    2015-01-07   601.0240
...         ...        ...
1225 2018-12-26   814.5940
1226 2018-12-27   177.6360
1227 2018-12-28  1657.3508
1228 2018-12-29  2915.5340
1229 2018-12-30   713.7900

[1230 rows x 2 columns]

In [51]:
px.line(data_daily_sales, x='Order Date', y='Sales', title='Daily Sales')

In [52]:
# Montly sales over years

In [53]:
data["year"] = data["Order Date"].dt.year

In [54]:
data["month"] = data["Order Date"].dt.month

In [55]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11

In [56]:
str(data.month) + "_" + str(data.year)

'0        8\n1        8\n2       12\n3       11\n4       11\n        ..\n9795     5\n9796    12\n9797    12\n9798    12\n9799    12\nName: month, Length: 9800, dtype: int64_0       2017\n1       2017\n2       2017\n3       2016\n4       2016\n        ... \n9795    2017\n9796    2016\n9797    2016\n9798    2016\n9799    2016\nName: year, Length: 9800, dtype: int64'

In [57]:
len(data)

9800

In [58]:
data.month[9799]

12

In [59]:
data.year[9799]

2016

In [62]:
data['Order month-year'] = str(data.month) + "-"+ str(data.year)

In [66]:
for i in range(len(data)):
  data['Order month-year'][i] = str(data.month[i]) + "-"+ str(data.year[i])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [67]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,8-2017
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,8-2017
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,12-2017
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,11-2016
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,11-2016

In [70]:
data['Order month-year'] = pd.to_datetime(data['Order month-year'])

In [71]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,2017-08-01
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,2017-08-01
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,2017-12-01
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,2016-11-01
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,2016-11-01

In [73]:
data_monthly_sales = data.groupby(['Order month-year']).agg({'Sales':'sum'}).reset_index()

In [74]:
data_monthly_sales

   Order month-year       Sales
0        2015-01-01  28828.2540
1        2015-02-01  12588.4840
2        2015-03-01  54027.6920
3        2015-04-01  24710.0160
4        2015-05-01  29520.4900
5        2015-06-01  29181.3346
6        2015-07-01  35194.5580
7        2015-08-01  37349.2655
8        2015-09-01  65956.3998
9        2015-10-01  34561.9470
10       2015-11-01  64369.4565
11       2015-12-01  63568.3107
12       2016-01-01  29347.3864
13       2016-02-01  20728.3520
14       2016-03-01  34489.6776
15       2016-04-01  38056.9685
16       2016-05-01  30761.5585
17       2016-06-01  28515.9082
18       2016-07-01  28573.3100
19       2016-08-01  49076.9300
20       2016-09-01  65352.9970
21       2016-10-01  31631.8890
22       2016-11-01  50009.1450
23       2016-12-01  52891.8832
24       2017-01-01  38048.1840
25       2017-02-01  48907.5900
26       2017-03-01  48990.1410
27       2017-04-01  42368.0480
28       2017-05-01  64836.2518
29       2017-06-01  37424.6810
30       2017-07-01  41761.9430
31       2017-08-01  45766.8144
32       2017-09-01  40692.3063
33       2017-10-01  52156.9580
34       2017-11-01  66392.5470
35       2017-12-01  72847.0855
36       2018-01-01  59767.0910
37       2018-02-01  48928.8334
38       2018-03-01  74748.6238
39       2018-04-01  37849.2156
40       2018-05-01  40882.4464
41       2018-06-01  46912.8475
42       2018-07-01  53942.7755
43       2018-08-01  75408.7840
44       2018-09-01  73153.3640
45       2018-10-01  65501.1622
46       2018-11-01  87997.6400
47       2018-12-01  56959.2358

In [76]:
px.line(data_monthly_sales, x='Order month-year', y='Sales', title = 'Monthly Sales')

In [77]:
# average sales by month

In [78]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,2017-08-01
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,2017-08-01
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,2017-12-01
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,2016-11-01
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,2016-11-01

In [79]:
data_avg_monthly_sales = data.groupby("month").agg({"Sales":"mean"}).reset_index()

In [80]:
data_avg_monthly_sales

    month       Sales
0       1  271.288549
1       2  244.688917
2       3  266.318864
3       4  206.923659
4       5  202.934898
5       6  207.653174
6       7  220.266003
7       8  259.827026
8       9  219.672999
9      10  229.528035
10     11  225.099488
11     12  231.236165

In [81]:
px.bar(data_avg_monthly_sales, x = 'month', y='Sales', title='Average sales by month')

In [82]:
# Average Sales by day of week

In [83]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,2017-08-01
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,2017-08-01
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,2017-12-01
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,2016-11-01
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,2016-11-01

In [84]:
data["Order Date"].dt.day_name()

0          Friday
1          Friday
2       Wednesday
3        Thursday
4        Thursday
          ...
9795       Sunday
9796     Thursday
9797     Thursday
9798     Thursday
9799     Thursday
Name: Order Date, Length: 9800, dtype: object

In [85]:
data['Order_weekday'] = data['Order Date'].dt.day_name()

In [86]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year,Order_weekday
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,2017-08-01,Friday
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,2017-08-01,Friday
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,2017-12-01,Wednesday
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,2016-11-01,Thursday
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,2016-11-01,Thursday

In [87]:
data_avg_sales_weekday = data.groupby('Order_weekday').agg({'Sales':'mean'}).reset_index()

In [88]:
data_avg_sales_weekday = data_avg_sales_weekday.sort_values(by='Sales')

In [89]:
data_avg_sales_weekday

  Order_weekday       Sales
3        Sunday  209.183929
5       Tuesday  211.989747
1        Monday  225.954714
0        Friday  230.053943
6     Wednesday  247.396663
2      Saturday  250.642387
4      Thursday  253.890178

In [90]:
px.bar(data_avg_sales_weekday, x='Order_weekday', y='Sales', title='Weekday sales')

In [91]:
# Total Sales by year

In [92]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year,Order_weekday
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,2017-08-01,Friday
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,2017-08-01,Friday
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,2017-12-01,Wednesday
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,2016-11-01,Thursday
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,2016-11-01,Thursday

In [93]:
data_sales_by_year = data.groupby("year").agg({"Sales":"sum"}).reset_index()

In [94]:
fig = px.bar(data_sales_by_year,x = "year", y = "Sales")
fig.update_xaxes(nticks = 4)

In [95]:
# Year over year growth : bir önceki yılın aynı dönemine kıyasla

In [96]:
data_sales_by_year

   year        Sales
0  2015  479856.2081
1  2016  459436.0054
2  2017  600192.5500
3  2018  722052.0192

In [97]:
data_sales_by_year["yoy"] = round(data_sales_by_year["Sales"].pct_change()*100, 2)

In [98]:
data_sales_by_year

   year        Sales    yoy
0  2015  479856.2081    NaN
1  2016  459436.0054  -4.26
2  2017  600192.5500  30.64
3  2018  722052.0192  20.30

In [99]:
fig = px.bar(data_sales_by_year, x = "year", y = "yoy")
fig.update_xaxes(nticks = 4)

In [100]:
# Top customers

In [101]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year,Order_weekday
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,2017-08-01,Friday
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,2017-08-01,Friday
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,2017-12-01,Wednesday
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,2016-11-01,Thursday
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,2016-11-01,Thursday

In [102]:
data_customer = data.groupby("Customer Name").agg({"Sales":"sum"}).sort_values(by= "Sales", ascending = False).reset_index()

In [103]:
data_customer

       Customer Name      Sales
0        Sean Miller  25043.050
1       Tamara Chand  19052.218
2       Raymond Buch  15117.339
3       Tom Ashbrook  14595.620
4      Adrian Barton  14473.571
..               ...        ...
788  Mitch Gastineau     16.739
789     Carl Jackson     16.520
790       Sung Chung     14.112
791     Lela Donovan      5.304
792    Thais Sissman      4.833

[793 rows x 2 columns]

In [104]:
px.bar(data_customer[0:20], x= "Customer Name", y= "Sales")

In [105]:
data.Segment.value_counts()

Consumer       5101
Corporate      2953
Home Office    1746
Name: Segment, dtype: int64

In [106]:
# Top cities

In [107]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,shipping_timeframe,_,year,month,Order month-year,Order_weekday
0,1,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,92,days,2017,8,2017-08-01,Friday
1,2,CA-2017-152156,2017-08-11,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,92,days,2017,8,2017-08-01,Friday
2,3,CA-2017-138688,2017-12-06,2017-12-10,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,days,2017,12,2017-12-01,Wednesday
3,4,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,6,days,2016,11,2016-11-01,Thursday
4,5,US-2016-108966,2016-11-10,2016-11-16,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,6,days,2016,11,2016-11-01,Thursday

In [108]:
data.groupby('City').agg({'Sales':'sum'}).sort_values(by='Sales', )

                    Sales
City
Abilene             1.392
Elyria              1.824
Jupiter             2.064
Pensacola           2.214
Ormond Beach        2.808
...                   ...
Philadelphia   108841.749
San Francisco  109041.120
Seattle        116106.322
Los Angeles    173420.181
New York City  252462.547

[529 rows x 1 columns]

In [109]:
data_city = data.groupby('City').agg({'Sales':'sum'}).sort_values(by='Sales', ascending=False).reset_index()

In [110]:
px.bar(data_city[0:5], x='City', y='Sales' )

In [111]:
data_city = data.groupby('Region').agg({'Sales':'sum'}).sort_values(by='Sales', ascending=False).reset_index()

In [112]:
px.bar(data_city[0:5], x='Region', y='Sales' )